type: object
additionalProperties: false
properties:
  project_name:
    type: string
  project_type:
    type: string
  details:
    type: string
required:
  - details
  - project_name
  - project_type
title: TopLevel
